src/SimpleShop.Web/Pages/Cart/Checkout.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpleShop.Application.Commands.Carts;
using SimpleShop.Application.Commands.Orders;
using SimpleShop.Application.Queries.Carts;
using SimpleShop.Domain.Entities;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace SimpleShop.Web.Pages.Cart
{
    public class CheckoutModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly UserManager<ApplicationUser> _userManager;

        public CheckoutModel(IMediator mediator, UserManager<ApplicationUser> userManager)
        {
            _mediator = mediator;
            _userManager = userManager;
        }

        public Domain.Entities.Cart Cart { get; set; }
        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required(ErrorMessage = "Imię jest wymagane.")]
            [RegularExpression(@"^[^0-9_!¡?÷?¿/\\+=@#$%ˆ&*(){}|~<>;:[\]]{2,}$", ErrorMessage = "Błędny format imienia.")]
            public string FirstName { get; set; }

            [Required(ErrorMessage = "Nazwisko jest wymagane.")]
            [RegularExpression(@"^[^0-9_!¡?÷?¿/\\+=@#$%ˆ&*(){}|~<>;:[\]]{2,}$", ErrorMessage = "Błędny format nazwiska.")]
            public string LastName { get; set; }

            [Required(ErrorMessage = "Nazwa ulicy jest wymagana.")]
            [RegularExpression(@"^[^0-9_!¡?÷?¿/\\+=@#$%ˆ&*(){}|~<>;:[\]]{2,}$", ErrorMessage = "Błędny format nazwy ulicy.")]
            public string Street { get; set; }

            [Required(ErrorMessage = "Numer budynku/lokalu jest wymagany.")]
            [RegularExpression(@"[1-9]\d*(\s*[-/]\s*[1-9]\d*)?(\s?[a-zA-Z])?", ErrorMessage = "Błędny format numeru budynku/lokalu.")]
            public string Apartment { get; set; }

            [Required(ErrorMessage = "Nazwa miejscowości jest wymagana.")]
            [RegularExpression(@"^[^0-9_!¡?÷?¿/\\+=@#$%ˆ&*(){}|~<>;:[\]]{2,}$", ErrorMessage = "Błędny format nazwy miejscowości.")]
            public string City { get; set; }

            [Required(ErrorMessage = "Kod pocztowy jest wymagany.")]
            [RegularExpression(@"^[a-z0-9][a-z0-9\- ]{0,10}[a-z0-9]$", ErrorMessage = "Błędny format kodu pocztowego.")]
            public string PostalCode { get; set; }

            [Required(ErrorMessage = "Numer telefonu komórkowego jest wymagany.")]
            [RegularExpression(@"(?<!\w)(\(?(\+|00)?48\)?)?[ -]?\d{3}[ -]?\d{3}[ -]?\d{3}(?!\w)", ErrorMessage = "Błędny format numeru komórkowego.")]
            public string Phone { get; set; }

            [Required(ErrorMessage = "Adres e-mail jest wymagany.")]
            [EmailAddress(ErrorMessage = "Błędny format adresu e-mail.")]
            public string Email { get; set; }

            [Required(ErrorMessage = "Metoda płatności jest wymagana.")]
            public string PaymentMethod { get; set; }
        }

        public async Task<IActionResult> OnGetAsync()
        {
            var userId = _userManager.GetUserId(User);

            Cart = await _mediator.Send(new GetCart.Query(userId));
            if (Cart.IsEmpty)
            {
                return RedirectToPage("Index");
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var userId = _userManager.GetUserId(User);

            Cart = await _mediator.Send(new GetCart.Query(userId));
            if (Cart.IsEmpty)
            {
                return RedirectToPage("Index");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var order = new Order
            {
                Id = Guid.NewGuid().ToString(),
                UserId = userId,
                Number = new Random().Next(1000, 4000)
            };

            var success = await _mediator.Send(new CreateOrder.Command(order));
            if (success)
            {
                var orderItems = new List<OrderItem>();
                foreach (var cartItem in Cart.Items)
                {
                    orderItems.Add(new OrderItem
                    {
                        Id = Guid.NewGuid().ToString(),
                        ProductId = cartItem.ProductId,
                        OrderId = order.Id,
                        Quantity = cartItem.Quantity,
                        Size = cartItem.Size
                    });
                }

                var orderDetails = new OrderDetails
                {
                    Id = Guid.NewGuid().ToString(),
                    OrderId = order.Id,
                    FirstName = Input.FirstName,
                    LastName = Input.LastName,
                    Street = Input.Street,
                    Apartment = Input.Apartment,
                    City = Input.City,
                    PostalCode = Input.PostalCode,
                    Phone = Input.Phone,
                    Email = Input.Email,
                    PaymentMethod = Input.PaymentMethod,
                    Total = Cart.GetTotal()
                };

                await _mediator.Send(new AddOrderItems.Command(orderItems));
                await _mediator.Send(new AddOrderDetails.Command(orderDetails));
                await _mediator.Send(new ClearCart.Command(Cart.Id));
            }

            return RedirectToPage("Summary", new { orderId = order.Id });
        }
    }
}

src/SimpleShop.Web/Pages/Cart/Index.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpleShop.Application.Commands.CartItems;
using SimpleShop.Application.Queries.Carts;
using SimpleShop.Domain.Entities;

namespace SimpleShop.Web.Pages.Cart
{
    public class IndexModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly UserManager<ApplicationUser> _userManager;

        public IndexModel(IMediator mediator, UserManager<ApplicationUser> userManager)
        {
            _mediator = mediator;
            _userManager = userManager;
        }

        public Domain.Entities.Cart Cart { get; private set; }

        public async Task<IActionResult> OnGetAsync()
        {
            var userId = _userManager.GetUserId(User);
            Cart = await _mediator.Send(new GetCart.Query(userId));

            return Page();
        }

        public async Task<IActionResult> OnPostDeleteItemAsync(string itemId)
        {
            var userId = _userManager.GetUserId(User);
            Cart = await _mediator.Send(new GetCart.Query(userId));

            var item = Cart.Items.SingleOrDefault(i => i.Id.Equals(itemId));
            if (item is not null)
            {
                await _mediator.Send(new DeleteCartItem.Command(item.Id));
            }

            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnPostUpdateItemAsync(string itemId, int quantity)
        {
            var userId = _userManager.GetUserId(User);
            Cart = await _mediator.Send(new GetCart.Query(userId));

            var item = Cart.Items.SingleOrDefault(i => i.Id.Equals(itemId));
            if (item is not null)
            {
                await _mediator.Send(new UpdateCartItem.Command(item.Id, quantity));
            }

            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnPostAddItemAsync(string productId, int size)
        {
            var userId = _userManager.GetUserId(User);
            Cart = await _mediator.Send(new GetCart.Query(userId));

            var item = Cart.Items.SingleOrDefault(i => i.ProductId.Equals(productId) && i.Size.Equals(size));
            if (item is not null)
            {
                await _mediator.Send(new UpdateCartItem.Command(item.Id, 1)); //w tej metodzie wywala errora
            }
            else
            {
                item = new CartItem
                {
                    Id = Guid.NewGuid().ToString(),
                    ProductId = productId,
                    CartId = Cart.Id,
                    Size = size,
                    Quantity = 1
                };
                await _mediator.Send(new AddCartItem.Command(item));
            }

            return RedirectToPage("Index");
        }
    }
}

src/SimpleShop.Web/Pages/Cart/Summary.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpleShop.Application.Queries.Orders;
using SimpleShop.Domain.Entities;

namespace SimpleShop.Web.Pages.Cart
{
    public class SummaryModel : PageModel
    {
        private readonly IMediator _mediator;

        public SummaryModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public Order Order { get; private set; }

        public async Task<IActionResult> OnGetAsync(string orderId)
        {
            Order = await _mediator.Send(new GetOrder.Query(orderId));
            if (Order is null)
            {
                return RedirectToPage("/Orders/Index", new { area = "" });
            }

            return Page();
        }
    }
}

src/SimpleShop.Web/Pages/Cart/Checkout.cshtml
@page
@model SimpleShop.Web.Pages.Cart.CheckoutModel
@{
    ViewData["Title"] = "Kasa";
}

<div class="container">
    <div class="columns is-centered">
        <div class="column is-7 m-1">
            
            <div class="block has-text-centered">
                <p class="is-size-4">Podsumowanie koszyka</p>
            </div>
            @foreach(var item in Model.Cart.Items)
            {
                <article class="media is-flex is-align-items-center">
                    <figure class="media-left">
                            <p class="image is-96x96">
                                <img src="~/assets/@item.Product.ImagePath">
                            </p>
                    </figure>
                    <div class="media-content">
                        <p class="is-size-5 mb-0">@item.Product.Name</p>
                        <p class="mb-0">Rozmiar: @item.Size</p>
                        <p class="mb-0">Ilość: @item.Quantity</p>
                    </div>
                    <div class="media-right">
                        <p class="has-text-weight-medium">@(item.Quantity * item.Product.Price) zł</p>
                    </div>
                </article>
            }
            <article class="media is-flex is-justify-content-space-between">
                <div class="media-left">
                    <p class="mb-2">Dostawa:</p>
                    <p class="has-text-weight-medium">Suma:</p>
                </div>
                <div class="media-right has-text-right">
                    <p class="has-text-success mb-2">DARMOWA</p>
                    <p class="has-text-weight-medium">@Model.Cart.GetTotal() zł</p>
                </div>
            </article>
        </div>
        <div class="column is-4 m-1">
            <form class="mb-5" method="post">
                <div class="block has-text-centered">
                    <p class="is-size-4">Dostawa</p>
                </div>
                <div asp-validation-summary="ModelOnly" class="has-text-danger"></div>
                <div class="field">
                    <div class="columns">
                        <div class="column">
                            <div class="control">
                                <input class="input" asp-for="Input.FirstName" type="text" placeholder="Imię">
                                <span asp-validation-for="Input.FirstName" class="has-text-danger"></span>
                            </div>
                        </div>
                        <div class="column">
                            <div class="control">
                                <input class="input" asp-for="Input.LastName" type="text" placeholder="Nazwisko">
                                <span asp-validation-for="Input.LastName" class="has-text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="field">
                    <div class="columns">
                        <div class="column is-8">
                            <div class="control has-icons-left">
                                <input class="input" asp-for="Input.Street" type="text" placeholder="Ulica">
                                <span class="icon is-small is-left">
                                    <i class='bx bx-home' ></i>
                                </span>
                                <span asp-validation-for="Input.Street" class="has-text-danger"></span>
                            </div>
                        </div>
                        <div class="column is-4">
                            <div class="control">
                                <input class="input" type="text" asp-for="Input.Apartment" placeholder="Numer budynku/lokalu">
                                <span asp-validation-for="Input.Apartment" class="has-text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="field">
                    <div class="columns">
                        <div class="column is-8">
                            <div class="control has-icons-left">
                                <input class="input" type="text" asp-for="Input.City" placeholder="Miasto">
                                <span class="icon is-small is-left">
                                    <i class='bx bxs-city' ></i>
                                </span>
                                <span asp-validation-for="Input.City" class="has-text-danger"></span>
                            </div>
                        </div>
                        <div class="column is-4">
                            <div class="control">
                                <input class="input" type="text" asp-for="Input.PostalCode" placeholder="Kod pocztowy">
                                <span asp-validation-for="Input.PostalCode" class="has-text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="field">
                    <div class="columns">
                        <div class="column">
                            <div class="control has-icons-left">
                                <input class="input" type="tel" asp-for="Input.Phone" placeholder="Nr telefonu komórkowego">
                                <span class="icon is-small is-left">
                                    <i class='bx bx-phone' ></i>
                                </span>
                                <span asp-validation-for="Input.Phone" class="has-text-danger"></span>
                            </div>
                        </div>
                        <div class="column">
                            <div class="control has-icons-left">
                                <input class="input" type="text" asp-for="Input.Email" placeholder="Adres e-mail">
                                <span class="icon is-left is-small">
                                    <i class='bx bx-envelope'></i>
                                </span>
                                <span asp-validation-for="Input.Email" class="has-text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="block has-text-centered">
                    <p class="is-size-4">Płatność</p>
                </div>
                <div class="control mb-5">
                    <div class="payment-selector has-text-centered">
                        <input type="radio" id="payment1" value="visa" asp-for="Input.PaymentMethod" />
                        <label for="payment1">
                            <span class="icon is-large">
                                <i class='bx bxl-visa bx-lg'></i>
                            </span>
                        </label>
                        <input type="radio" id="payment2" value="mastercard" asp-for="Input.PaymentMethod" />
                        <label for="payment2">
                            <span class="icon is-large">
                                <i class='bx bxl-mastercard bx-lg' ></i>
                            </span>
                        </label>
                        <input type="radio" id="payment3" value="paypal" asp-for="Input.PaymentMethod" />
                        <label for="payment3">
                            <span class="icon is-large">
                                <i class='bx bxl-paypal bx-lg' ></i>
                            </span>
                        </label>
                    </div>
                    <span asp-validation-for="Input.PaymentMethod" class="has-text-danger"></span>
                </div>
                <div class="has-text-centered">
                    <button type="submit" class="button is-success is-medium">Zapłać @Model.Cart.GetTotal() zł</button>
                </div>
            </form>
        </div>     
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/SimpleShop.Web/Pages/Cart/Index.cshtml
@page 
@model SimpleShop.Web.Pages.Cart.IndexModel
@{
    ViewData["Title"] = "Koszyk";
}

<div class="container">
    @if (!Model.Cart.IsEmpty)
    {
        <div class="columns is-centered is-vcentered">
            <div class="column">
                @foreach(var item in Model.Cart.Items)
                {
                    <article class="media">
                        <figure class="media-left">
                            <p class="image is-128x128">
                                <img src="~/assets/@item.Product.ImagePath">
                            </p>
                        </figure>
                        <div class="media-content">
                            <div class="content">
                                <p class="is-size-5 mb-0">@item.Product.Name</p>
                                <p class="mb-0 has-text-weight-medium">@(item.Product.Price * item.Quantity) zł</p>
                                <p class="mb-0">Rozmiar: @item.Size</p>
                                <div class="columns">
                                    <div class="column is-4 is-8-mobile">
                                        <div class="field has-addons">
                                            <form method="post" asp-page="/Cart/Index" asp-area="" asp-page-handler="UpdateItem">
                                                <p class="control">
                                                    <button class="button" type="submit" >-</button>
                                                    <input type="hidden" name="itemId" value="@item.Id" />
                                                    <input type="hidden" name="quantity" value="-1" />
                                                </p>
                                            </form>
                                            <p class="control">
                                                <input class="input" type="text" value="@item.Quantity" readonly style="text-align: center">
                                            </p>
                                            <form method="post" asp-page="/Cart/Index" asp-area="" asp-page-handler="UpdateItem">
                                                <p class="control">
                                                    <button class="button" type="submit">+</button>
                                                    <input type="hidden" name="itemId" value="@item.Id" />
                                                    <input type="hidden" name="quantity" value="1" />
                                                </p>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="media-right">
                            <form method="post" asp-page="/Cart/Index" asp-area="" asp-page-handler="DeleteItem">
                                <button class="delete" type="submit" name="itemId" value="@item.Id"></button>
                            </form>
                        </div>
                    </article>
                }
                <article class="media is-flex is-justify-content-space-between">
                    <div class="media-left">
                        <p class="mb-2">Dostawa:</p>
                        <p class="has-text-weight-medium">Suma:</p>
                    </div>
                    <div class="media-right">
                        <p class="has-text-success mb-2">DARMOWA</p>
                        <p class="has-text-weight-medium">@Model.Cart.GetTotal() zł</p>
                    </div>
                </article>
                <div class="field mt-2">
                    <div class="control is-flex is-justify-content-center">
                        <a class="button is-dark" asp-page="Checkout" asp-area="">Przejdź do kasy</a>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="block has-text-centered">
            <span class="icon is-large">
                <i class='bx bx-cart bx-lg'></i>
            </span>
        </div>
        <div class="has-text-centered">
            <p class="has-text-weight-medium subtitle">Wygląda na to, że twój koszyk jest pusty!</p>
            <a class="button is-outlined" asp-area="" asp-page="/Index">Powrót do sklepu</a>
        </div>
    }
</div>

src/SimpleShop.Web/Pages/Cart/Summary.cshtml
@page "{orderId:Guid}"
@model SimpleShop.Web.Pages.Cart.SummaryModel
@{
    ViewData["Title"] = $"Zamówienie #{Model.Order.Number}";
}

<div class="container has-text-centered">
    <div class="block">
            <span class="icon is-large">
                <i class='bx bx-receipt bx-lg'></i>
            </span>
        </div>
        <div>
            <p class="title has-text-weight-medium">Dziękujemy, @Model.Order.Details.FirstName!</p>
            <p class="subtitle">Zamówienie #@Model.Order.Number zostało złożone.</p>
            <a class="button is-outlined" asp-area="" asp-page="/Orders/Index">Moje zamówienia</a>
        </div>
</div>