src/SimpleShop.Web/Pages/Cart/Index.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpleShop.Application.Commands.CartItems;
using SimpleShop.Application.Queries.Carts;
using SimpleShop.Domain.Entities;

namespace SimpleShop.Web.Pages.Cart
{
    public class IndexModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly UserManager<ApplicationUser> _userManager;

        public IndexModel(IMediator mediator, UserManager<ApplicationUser> userManager)
        {
            _mediator = mediator;
            _userManager = userManager;
        }

        public Domain.Entities.Cart Cart { get; private set; }

        public async Task<IActionResult> OnGetAsync()
        {
            var userId = _userManager.GetUserId(User);
            Cart = await _mediator.Send(new GetCart.Query(userId));

            return Page();
        }

        public async Task<IActionResult> OnPostDeleteItemAsync(string itemId)
        {
            var userId = _userManager.GetUserId(User);
            Cart = await _mediator.Send(new GetCart.Query(userId));

            var item = Cart.Items.SingleOrDefault(i => i.Id.Equals(itemId));
            if (item is not null)
            {
                await _mediator.Send(new DeleteCartItem.Command(item.Id));
            }

            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnPostUpdateItemAsync(string itemId, int quantity)
        {
            var userId = _userManager.GetUserId(User);
            Cart = await _mediator.Send(new GetCart.Query(userId));

            var item = Cart.Items.SingleOrDefault(i => i.Id.Equals(itemId));
            if (item is not null)
            {
                await _mediator.Send(new UpdateCartItem.Command(item.Id, quantity));
            }

            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnPostAddItemAsync(string productId, int size)
        {
            var userId = _userManager.GetUserId(User);
            Cart = await _mediator.Send(new GetCart.Query(userId));

            var item = Cart.Items.SingleOrDefault(i => i.ProductId.Equals(productId) && i.Size.Equals(size));
            if (item is not null)
            {
                await _mediator.Send(new UpdateCartItem.Command(item.Id, 1)); //w tej metodzie wywala errora
            }
            else
            {
                item = new CartItem
                {
                    Id = Guid.NewGuid().ToString(),
                    ProductId = productId,
                    CartId = Cart.Id,
                    Size = size,
                    Quantity = 1
                };
                await _mediator.Send(new AddCartItem.Command(item));
            }

            return RedirectToPage("Index");
        }
    }
}

src/SimpleShop.Web/Pages/Products/Index.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpleShop.Application.Queries.Products;
using SimpleShop.Domain.Entities;

namespace SimpleShop.Web.Pages.Products
{
    public class IndexModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly UserManager<ApplicationUser> _userManager;

        public IndexModel(IMediator mediator, UserManager<ApplicationUser> userManager)
        {
            _mediator = mediator;
            _userManager = userManager;
        }

        public Product Product { get; set; }
        [BindProperty]
        public int Size { get; set; }
        public IEnumerable<Product> RelatedProducts { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            Product = await _mediator.Send(new GetProduct.Query(id));
            if(Product is null)
            {
                return RedirectToPage("/Index", new { area = "" });
            }
            RelatedProducts = await _mediator.Send(new GetRelatedProducts.Query(Product));

            return Page();
        }
    }
}

src/SimpleShop.Web/Pages/Products/Index.cshtml
@page "{id:Guid}"
@model SimpleShop.Web.Pages.Products.IndexModel

@using Microsoft.AspNetCore.Identity
@using SimpleShop.Domain.Entities
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if(Model.Product is not null)
{
    {
        ViewData["Title"] = @Model.Product.Name;
    }
    <div class="container">
        <div class="columns">
            <div class="column">
                <figure class="image">
                    <img src="~/assets/@Model.Product.ImagePath" />
                </figure>
            </div>
            <div class="column is-4">
                <p class="is-size-3">@Model.Product.Name</p>
                <p class="is-size-4 has-text-weight-medium">@Model.Product.Price zł</p>
                <div class="my-5 py-5 has-border-y">
                    @if(SignInManager.IsSignedIn(User))
                    {
                        <form method="post" asp-page="/Cart/Index" asp-area="" asp-page-handler="AddItem" asp-route-productId="@Model.Product.Id" asp-route-size="@Model.Size">
                            <div class="field">
                                <label class="label">Rozmiar</label>
                                <div class="control">
                                    <div class="select">
                                        <select asp-for="Size">
                                            <option selected value="42">42</option>
                                            <option value="43">43</option>
                                            <option value="44">44</option>
                                            <option value="45">45</option>
                                            <option value="46">46</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="field">
                                <div class="control">
                                    <button class="button is-dark" type="submit">
                                        Dodaj do koszyka
                                    </button>
                                </div>
                            </div>
                            <div class="field">
                                <span class="icon-text">
                                    <span class="icon">
                                        <i class='bx bx-package'></i>
                                    </span>
                                    <span class="is-underlined">Darmowa dostawa</span>
                                </span>
                            </div>
                        </form>
                    }
                    else
                    {
                        <p class="has-text-danger">Zaloguj się aby kupić @Model.Product.Name</p>
                    }
                </div>           
                <p class="is-size-5 block">Opis</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec suscipit, dui quis luctus tincidunt, metus arcu pulvinar nunc, quis aliquet neque risus id purus. Suspendisse potenti. Phasellus suscipit varius sapien sit amet egestas. Vivamus molestie augue vitae aliquam eleifend. Vivamus eu justo sit amet diam laoreet faucibus vel vel mi. Quisque dictum mattis mi, vel venenatis diam maximus quis. Etiam at tristique ex. Maecenas ornare mattis bibendum.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent et aliquam velit. Proin scelerisque nisi eros, sed vulputate lorem mollis et. Praesent ultricies felis vel nibh euismod gravida.</p>
            </div>
        </div>
        <div class="block has-text-centered">
            <p class="is-size-4">
                Podobne produkty
            </p>
        </div>
        <div class="columns">        
            @if(Model.RelatedProducts is not null)
            {
                @foreach(var relatedProduct in Model.RelatedProducts)
                {
                    <div class="column is-flex is-justify-content-center">
                        <div class="card">
                            <div class="card-image">
                                <a asp-route-id="@relatedProduct.Id" asp-page="/Products/Index" asp-area="">
                                    <figure class="image" style="width: 256px; height: 256px;">
                                        <img src="~/assets/@relatedProduct.ImagePath">
                                    </figure>
                                </a>
                            </div>
                            <div class="card-content pt-1 pl-0">
                                <p class="is-size-5">@relatedProduct.Name</p>
                                <p class="has-text-weight-medium">@relatedProduct.Price zł</p>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
}