src/SimpleShop.Web/ViewComponents/NavbarViewComponent.cs
using MediatR;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SimpleShop.Application.Queries.Carts;
using SimpleShop.Domain.Entities;

namespace SimpleShop.Web.ViewComponents
{
    public class NavbarViewComponent : ViewComponent
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMediator _mediator;

        public NavbarViewComponent(UserManager<ApplicationUser> userManager, IMediator mediator)
        {
            _userManager = userManager;
            _mediator = mediator;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            Cart cart = null;

            if(user is not null)
            {
                cart = await _mediator.Send(new GetCart.Query(user.Id));
            }

            return View(cart);
        }
    }
}

src/SimpleShop.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewData["Title"] | SimpleShop</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel='stylesheet' href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bulma/bulma-divider.min.css" />
    <link rel="stylesheet" href="~/lib/bulma/bulma-list.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SimpleShop.Web.styles.css" asp-append-version="true" />
</head>
<body class="has-navbar-fixed-top">
    @await Component.InvokeAsync("Navbar")
    <section class="section" id="wrapper">
        @RenderBody()
    </section>
    <footer class="footer has-border">
        <div class="content has-text-centered">
            <p><strong>SimpleShop</strong> created by <a href="https://github.com/Zimeek" target="_blank">Zimeek</a></p>
            <a href="https://bulma.io" target="_blank">
                <img src="~/assets/bulma-logo.png" style="width: 128px; height: 24px;" />
            </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/SimpleShop.Web/Pages/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Identity
@using SimpleShop.Domain.Entities
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<nav class="navbar is-fixed-top has-shadow is-white has-border" role="navigation">
    <div class="navbar-brand">
        <a class="navbar-item is-size-4" asp-page="/Index" asp-area="">SimpleShop</a>
        <a class="navbar-burger" role="button" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>
    <div class="navbar-menu" id="navbar-menu">
        <div class="navbar-end">
            @if(SignInManager.IsSignedIn(User))
            {
                <a class="navbar-item" asp-page="/Cart/Index" asp-area="">
                    <span class="icon-text">
                        <span class="icon is-hidden-touch">
                            <i class='bx bx-cart bx-sm'></i>
                        </span>
                        <span class="is-hidden-desktop">Koszyk</span>
                    </span>
                </a>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link is-arrowless">
                    <span class="icon-text">
                        <span class="icon is-hidden-touch">
                            <i class='bx bx-user bx-sm'></i>
                        </span>                    
                        <span class="is-hidden-desktop">Konto</span>
                    </span>
                    </a>
                    <div class="navbar-dropdown is-right">
                        <a class="navbar-item">@UserManager.GetUserName(User)</a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" asp-page="/Orders/Index" asp-area="">Moje zamówienia</a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" asp-area="Identity" asp-page="/Account/Logout">Wyloguj</a>
                    </div>
                </div>
            }
            else
            {
                <a class="navbar-item" asp-page="/Account/Login" asp-area="Identity">                  
                    <span class="icon">
                        <i class='bx bx-user bx-sm'></i>
                    </span>
                </a>
            }
        </div>
    </div>
</nav>